version: '3.7'
services:
# FIXME configure regular app
  acceptance-app:
    image: kmaster/acceptance-app:latest
    container_name: acceptance-app
    restart: always
    environment:
      ACCEPTANCE_APP_PORT: 80
      # FIXME configure/define URL for acceptance tests to point to real app + acceptance app
      # FIXME configure real + acceptance app to point to the same DB (spin up postgres via docker here)
    ports:
      - 8081:80
